name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ThomasWecker/kchuch.me
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
    - name: Push CNAME file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        source_file: 'CNAME'
        destination_repo: 'ThomasWecker/kchuch.me'
        user_email: 'thomas.wecker@icloud.com'
        user_name: 'ThomasWecker'
        commit_message: 'create CNAME'
